# Generated by Django 6.1.1 on 2026-09-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Sovg'a nomi")),
                ('rarity', models.CharField(choices=[('COMMON', "Ko'k (Common)"), ('RARE', 'Siyohrang (Rare)'), ('EPIC', 'Pushti (Epic)'), ('LEGENDARY', 'Oltin (Legendary)')], default='COMMON', max_length=20, verbose_name='Kamyoblik darajasi')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rasm yoki Ikonka URL')),
                ('probability', models.IntegerField(default=10, verbose_name="Ehtimollik og'irligi (0-100%)")),
                ('valid_days', models.IntegerField(default=3, verbose_name='Yutuq amal qilish muddati (kun)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivligi')),
            ],
            options={
                'verbose_name': "Sovg'a",
                'verbose_name_plural': "Sovg'alar",
                'ordering': ['-probability', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('school_number', models.CharField(max_length=50, verbose_name='Maktab raqami')),
                ('grade_class', models.CharField(max_length=20, verbose_name='Sinf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "O'quvchi Lead",
                'verbose_name_plural': "O'quvchilar Leads",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Promokod')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('USED', 'Ishlatilgan'), ('EXPIRED', "Muddati o'tgan")], default='ACTIVE', max_length=20, verbose_name='Holati')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqt')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnings', to='app_main.studentlead', verbose_name="O'quvchi")),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winnings', to='app_main.prize', verbose_name="Yutib olingan sovg'a")),
            ],
            options={
                'verbose_name': 'Yutuq Natijasi',
                'verbose_name_plural': 'Yutuqlar Jurnali',
                'ordering': ['-created_at'],
            },
        ),
    ]
