# Generated by Django 6.1.1 on 2026-09-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlead',
            name='extra_spins',
            field=models.IntegerField(default=0, verbose_name="Qo'shimcha spinlar soni"),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='app_main.studentlead', verbose_name="Taklif qilgan o'quvchi"),
        ),
    ]
