# Generated by Django 6.1.1 on 2026-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_studentlead_extra_spins_studentlead_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name="Sovg'a rasmi (fayl)"),
        ),
        migrations.AlterField(
            model_name='prize',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Rasm yoki Ikonka URL (fayl o'rniga)"),
        ),
    ]
