# Generated by Django 6.1.1 on 2026-09-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_clear_broken_seed_image_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kategoriya rasmi (fayl)')),
                ('icon', models.CharField(blank=True, help_text='Rasm yuklanmasa shu emoji ishlatiladi. Masalan: 🎮', max_length=8, verbose_name='Ikonka (emoji)')),
                ('sort_order', models.IntegerField(default=0, help_text='Kichik raqam yuqorida turadi', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bu kategoriyadagi sovg'alar barabanda qatnashmaydi", verbose_name='Aktivligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "Sovg'a kategoriyasi",
                'verbose_name_plural': "Sovg'a kategoriyalari",
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='prize',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='app_main.prizecategory', verbose_name='Kategoriyasi'),
        ),
    ]
