# Generated by Django 6.1.1 on 2026-09-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_prizecategory_prize_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlead',
            name='grade_class',
        ),
        migrations.RemoveField(
            model_name='studentlead',
            name='school_number',
        ),
        migrations.AddField(
            model_name='prize',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Google Maps havolasidan avtomatik olinadi', null=True, verbose_name='Kenglik (latitude)'),
        ),
        migrations.AddField(
            model_name='prize',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik (longitude)'),
        ),
        migrations.AddField(
            model_name='prize',
            name='pickup_address',
            field=models.CharField(blank=True, help_text="QR-kod ostida ko'rinadi. Masalan: Toshkent sh., Yoshlar Texnoparki", max_length=255, verbose_name="Sovg'ani olish manzili"),
        ),
    ]
