# Generated by Django 6.1.1 on 2026-09-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_remove_studentlead_grade_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Rasmiylashtirilmagan'), ('ACTIVE', 'Aktiv'), ('USED', 'Ishlatilgan'), ('EXPIRED', "Muddati o'tgan")], default='ACTIVE', max_length=20, verbose_name='Holati'),
        ),
    ]
