# Generated by Django 6.1.1 on 2026-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_winning_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Oddiy'), ('RARE', 'Noyob'), ('EPIC', 'Epik'), ('LEGENDARY', 'Afsonaviy')], default='COMMON', max_length=20, verbose_name='Kamyoblik darajasi'),
        ),
    ]
