# Generated by Django 6.1.1 on 2026-09-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def confirm_existing_referrals(apps, schema_editor):
    """
    Eski qoidada do'st /start bosishi bilan hisoblangan va bonus spinlar
    allaqachon berilgan. Balanslar o'zgarmasligi uchun mavjud referallarni
    tasdiqlangan deb belgilaymiz.
    """
    StudentLead = apps.get_model('app_main', 'StudentLead')
    for lead in StudentLead.objects.filter(referrer__isnull=False, referral_confirmed_at__isnull=True):
        lead.referral_confirmed_at = lead.created_at
        lead.save(update_fields=['referral_confirmed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_uzbek_rarity_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirilsa — cheksiz. 0 ga tushsa sovg'a barabandan chiqadi.", null=True, verbose_name='Qoldiq (dona)'),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='referral_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taklif tasdiqlangan vaqt'),
        ),
        migrations.AddField(
            model_name='winningresult',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_winnings', to=settings.AUTH_USER_MODEL, verbose_name="Sovg'ani bergan xodim"),
        ),
        migrations.RunPython(confirm_existing_referrals, migrations.RunPython.noop),
    ]
