# Generated by Django 6.1.1 on 2026-09-23 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_stock_referral_confirm_used_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlead',
            name='bot_blocked',
            field=models.BooleanField(default=False, verbose_name='Botni bloklagan'),
        ),
        migrations.AddField(
            model_name='winningresult',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eslatma yuborilgan'),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000, verbose_name='Xabar matni')),
                ('audience', models.CharField(choices=[('ALL', 'Botdagi barcha foydalanuvchilar'), ('REGISTERED', "Forma to'ldirganlar"), ('ACTIVE_PRIZE', "Olib ketilmagan sovg'asi borlar"), ('NO_SPIN', 'Hali barabanni aylantirmaganlar'), ('HAS_SPINS', 'Ishlatilmagan aylantirishi borlar')], default='ALL', max_length=20, verbose_name='Kimlarga')),
                ('with_button', models.BooleanField(default=True, verbose_name="«Ochish» tugmasi qo'shilsin")),
                ('status', models.CharField(choices=[('SENDING', 'Yuborilmoqda'), ('DONE', 'Yakunlandi'), ('CANCELLED', 'Bekor qilindi')], default='SENDING', max_length=20, verbose_name='Holati')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Jami qabul qiluvchilar')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Yuborildi')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Yetib bormadi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Yuborgan xodim')),
            ],
            options={
                'verbose_name': 'Ommaviy xabar',
                'verbose_name_plural': 'Ommaviy xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('parse_mode', models.CharField(blank=True, default='', max_length=10)),
                ('with_button', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('BROADCAST', 'Ommaviy xabar'), ('REMINDER', 'Muddat eslatmasi'), ('REFERRAL', 'Referal bildirishnomasi')], max_length=20, verbose_name='Turi')),
                ('status', models.CharField(choices=[('PENDING', 'Navbatda'), ('SENT', 'Yuborildi'), ('FAILED', 'Yetib bormadi')], default='PENDING', max_length=10, verbose_name='Holati')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_main.broadcast')),
            ],
            options={
                'verbose_name': 'Bot xabari',
                'verbose_name_plural': 'Bot xabarlari navbati',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='app_main_bo_status_d30bb2_idx')],
            },
        ),
    ]
