# Generated by Django 6.1.1 on 2026-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_bot_outbox_broadcasts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('chat_id', models.CharField(help_text='Ochiq kanal: @texnopark_uz. Yopiq kanal: -1001234567890', max_length=100, verbose_name='Kanal username yoki ID')),
                ('invite_link', models.URLField(blank=True, help_text='Yopiq kanal uchun majburiy (https://t.me/+AbCd...). Ochiq kanalda avtomatik', verbose_name='Taklif havolasi')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Majburiy kanal',
                'verbose_name_plural': 'Majburiy kanallar',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_required', models.BooleanField(default=True, help_text='Yoqilsa, barabanni aylantirishdan oldin quyidagi kanallarga obuna tekshiriladi', verbose_name='Majburiy obuna yoqilgan')),
                ('campaign_start', models.DateTimeField(blank=True, help_text="Bo'sh — darhol boshlangan", null=True, verbose_name='Aksiya boshlanishi')),
                ('campaign_end', models.DateTimeField(blank=True, help_text="Bo'sh — muddatsiz. Tugagach baraban yopiladi, yutuqlarni olish davom etadi", null=True, verbose_name='Aksiya tugashi')),
                ('campaign_closed_message', models.CharField(blank=True, help_text="Bo'sh qolsa standart matn ko'rsatiladi", max_length=255, verbose_name='Aksiya yopiq paytdagi matn')),
                ('daily_bonus_enabled', models.BooleanField(default=False, help_text="Har kuni MiniApp'ga kirgan foydalanuvchi +1 aylantirish oladi", verbose_name='Kunlik bonus')),
                ('referrals_per_spin', models.PositiveSmallIntegerField(default=3, verbose_name="Necha do'st = +1 aylantirish")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sozlamalar',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
        migrations.AddField(
            model_name='studentlead',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi kunlik bonus'),
        ),
    ]
