# Generated by Django 6.1.1 on 2026-09-23 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def log_existing_extra_spins(apps, schema_editor):
    """
    Mavjud extra_spins qiymatlari tarixga "manbasi noma'lum" sifatida yoziladi —
    shu nuqtadan boshlab har bir yangi spin sababi bilan qayd etiladi.
    """
    StudentLead = apps.get_model('app_main', 'StudentLead')
    SpinGrant = apps.get_model('app_main', 'SpinGrant')
    SpinGrant.objects.bulk_create([
        SpinGrant(lead=lead, amount=lead.extra_spins, reason='LEGACY',
                  note="v1.3.1 gacha to'plangan qo'shimcha spinlar")
        for lead in StudentLead.objects.filter(extra_spins__gt=0)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_settings_channels_daily_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_wins_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='0 — cheklanmagan', verbose_name='Bir odamga kunlik yutuq limiti'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_wins_total',
            field=models.PositiveSmallIntegerField(default=3, help_text="Qo'shimcha spinlar qancha bo'lishidan qat'i nazar. 0 — cheklanmagan", verbose_name='Bir odamga jami yutuq limiti'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unique_phone_required',
            field=models.BooleanField(default=True, help_text="Raqam boshqa akkauntda yutuq olgan bo'lsa, yangi yutuq rasmiylashtirilmaydi", verbose_name='Bitta telefon — bitta ishtirokchi'),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
        migrations.AlterField(
            model_name='winningresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Rasmiylashtirilmagan'), ('ACTIVE', 'Aktiv'), ('USED', 'Ishlatilgan'), ('EXPIRED', "Muddati o'tgan"), ('CANCELLED', 'Bekor qilingan')], default='ACTIVE', max_length=20, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='SpinGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Manfiy — olib tashlangan', verbose_name='Miqdor')),
                ('reason', models.CharField(choices=[('REFERRAL', "Do'st taklifi"), ('DAILY_BONUS', 'Kunlik bonus'), ('STAFF', 'Xodim tomonidan'), ('LEGACY', "v1.3.1 gacha berilgan (manbasi noma'lum)")], max_length=20, verbose_name='Sabab')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_grants', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_grants', to='app_main.studentlead', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Spin tarixi',
                'verbose_name_plural': 'Spinlar tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(log_existing_extra_spins, migrations.RunPython.noop),
    ]
